'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('fs'); const path=require('path');
const Database=require('better-sqlite3'); const {resolveConversation}=require('../src/conversation/conversationResolver');
const {ConversationStateRepository,blank}=require('../src/conversation/conversationStateRepository'); const {run}=require('../src/conversation/runtime');
const fixtures=require('./fixtures/conversation_companies.json');
function scope(tenant='t1',conversation='c1',contact='u1',channel='whatsapp'){return {tenant_id:tenant,conversation_id:conversation,contact_id:contact,channel};}
function resolve(message,state,entities=[],caps=[],recent=[],id='m1'){return resolveConversation({...scope(state.tenant_id,state.conversation_id,state.contact_id,state.channel),message_id:id,current_message:message,recent_messages:recent,conversation_state:state,known_entities:entities,available_business_capabilities:caps}).resolution;}
test('greetings preserve active topic and recall survives them',()=>{const s=blank(scope()); let a=resolve('Tell me about Aurora Link',s,fixtures[0].entities,fixtures[0].capabilities,[],'1'); let s2=require('../src/conversation/stateReducer').reduceState(s,a); const topic=s2.active_topic.entity_id; a=resolve('Hello',s2,fixtures[0].entities,[],[],'2'); s2=require('../src/conversation/stateReducer').reduceState(s2,a); assert.equal(s2.active_topic.entity_id,topic); const r=resolve('What did I ask about?',s2,fixtures[0].entities,[],[{id:'1',role:'user',content:'Tell me about Aurora Link'},{id:'2',role:'user',content:'Hello'}],'3'); assert.match(r.direct_response,/Aurora Link/); assert.equal(r.requires_rag,false);});
for(const company of fixtures)test(`transaction continuation is generic: ${company.tenant}`,()=>{let s=blank(scope(company.tenant)); const q=resolve(`Tell me about ${company.entities[0].display_name}`,s,company.entities,company.capabilities,[],'1'); s=require('../src/conversation/stateReducer').reduceState(s,q); const phrase=company.capabilities[0].capability==='booking_request'?'Book it':'I want it'; const a=resolve(phrase,s,company.entities,company.capabilities,[],'2'); assert.equal(a.active_topic.entity_id,q.active_topic.entity_id); assert.equal(a.message_type,'transactional'); assert.ok(a.required_slots.length);});
test('unknown and ambiguous references clarify',()=>{const s=blank(scope()); assert.equal(resolve('I want it',s,[],[],[],'1').requires_clarification,true); const entities=[{canonical_name:'Alpha Pump',display_name:'Alpha Pump',entity_type:'product'},{canonical_name:'Beta Pump',display_name:'Beta Pump',entity_type:'product'}]; let a=resolve('Compare Alpha Pump and Beta Pump',s,entities,[],[],'2'); let s2=require('../src/conversation/stateReducer').reduceState(s,a); a=resolve('I want to buy it',s2,entities,[{capability:'purchase_request',supported_entity_types:['product'],required_slots:['entity_id']}],[],'3'); assert.equal(a.requires_clarification,true); assert.match(a.clarification_question,/Alpha Pump|Beta Pump/);});
test('correction restores first user-selected entity',()=>{const entities=[{canonical_name:'Alpha Pump',display_name:'Alpha Pump',entity_type:'product'},{canonical_name:'Beta Pump',display_name:'Beta Pump',entity_type:'product'}]; let s=blank(scope()); let a=resolve('Alpha Pump',s,entities,[],[],'1'); s=require('../src/conversation/stateReducer').reduceState(s,a); a=resolve('Beta Pump',s,entities,[],[],'2'); s=require('../src/conversation/stateReducer').reduceState(s,a); a=resolve('No, I meant the first one',s,entities,[],[],'3'); assert.equal(a.active_topic.canonical_name,'Alpha Pump'); assert.equal(a.message_type,'correction');});
test('reported conversation resolves generically without a product-specific branch',()=>{const known=[{canonical_name:'Mesh',display_name:'Mesh',entity_type:'product'}],caps=[{capability:'purchase_request',supported_entity_types:['product'],required_slots:['entity_id','quantity'],confirmation_required:true,execution_mode:'human_handoff'}]; let s=blank(scope()),recent=[]; for(const [id,text] of [['1','Do you have Mesh?'],['2','Hello']]){const a=resolve(text,s,known,caps,recent,id);s=require('../src/conversation/stateReducer').reduceState(s,a);recent.push({id,role:'user',content:text});} let a=resolve('What did I ask you about?',s,known,caps,recent,'3'); assert.match(a.direct_response,/Mesh/); a=resolve('I want to buy',s,known,caps,recent,'4'); assert.equal(a.active_topic.canonical_name,'Mesh');assert.deepEqual(a.required_slots,['quantity']);});
test('assistant text cannot select or replace an entity',()=>{const known=[{canonical_name:'User Choice',display_name:'User Choice',entity_type:'product'},{canonical_name:'Assistant Suggestion',display_name:'Assistant Suggestion',entity_type:'product'}];let s=blank(scope());let a=resolve('User Choice',s,known,[],[],'1');s=require('../src/conversation/stateReducer').reduceState(s,a);a=resolve('How much is it?',s,known,[],[{id:'a',role:'assistant',content:'Try Assistant Suggestion'}],'2');assert.equal(a.active_topic.canonical_name,'User Choice');});
test('SQLite state is idempotent, rebuildable and isolated',()=>{const db=new Database(':memory:'); db.exec(fs.readFileSync(path.join(__dirname,'../src/database/migrations/035_conversation_resolver_v2.sql'),'utf8')); const repo=new ConversationStateRepository(db); const input={...scope(),message_id:'stable',current_message:'Aurora Link',recent_messages:[],known_entities:fixtures[0].entities,available_business_capabilities:[]}; const one=run(input,repo),two=run(input,repo); assert.equal(one.state.state_version,1); assert.equal(two.state.state_version,1); assert.equal(repo.events(scope()).length,1); assert.deepEqual(repo.rebuild(scope()).active_topic,one.state.active_topic); assert.equal(repo.get(scope('t2')).active_topic,null); db.close();});
test('optimistic concurrency rejects stale writes',()=>{const db=new Database(':memory:'); db.exec(fs.readFileSync(path.join(__dirname,'../src/database/migrations/035_conversation_resolver_v2.sql'),'utf8')); const repo=new ConversationStateRepository(db),s=scope(); repo.commit(s,{messageId:'1',nextState:blank(s),expectedVersion:0}); assert.throws(()=>repo.commit(s,{messageId:'2',nextState:blank(s),expectedVersion:0}),e=>e.code==='CONVERSATION_STATE_CONFLICT'); db.close();});
